/**
 * ESL PWA — registry reader
 *
 * The one place the app learns what exists. Everything here is a lookup over
 * data the generator already resolved; nothing is derived, parsed or guessed.
 *
 * THE RULE THIS FILE EXISTS TO KEEP
 *   IDs are opaque. "LTR-A-NAME", "U2-BA" and "U3-AT" are frozen tokens from a
 *   structure that was stood down. "U2-" does not mean Unit 2. Nothing in this
 *   file reads a prefix, splits on a dash, or infers a group, part or letter
 *   from an ID. Group, part, letter and shape are DECLARED fields — read them.
 *
 * The registry is generated by scripts/build-registry.mjs into out/, which is
 * gitignored, so `npm run dev` and `npm run build` generate it first. If the
 * import below fails, the generator has not run — that is the bug, not this.
 */

import registry from '../../out/esl_unit_registry.json'

/* One pass, at module load. Every lookup after this is a Map hit. */
const ITEMS = new Map()
const LEGACY = new Map()
for (const container of Object.values(registry.groups)) {
  for (const item of container.items) {
    ITEMS.set(item.id, item)
    for (const key of item.legacyKeys || []) LEGACY.set(key, item.id)
  }
}

export const schemaVersion = registry.schemaVersion
export const gating = registry.gating

/** Containers in declared order, populated or not. The waterfall's spine. */
export function structure () {
  return registry.structure
}

/** Only the containers that actually have entries. Today: G1. */
export function groups () {
  return registry.structure
    .filter(s => s.populated)
    .map(s => registry.groups[s.id])
}

/** One container by its declared id, or null. */
export function group (groupId) {
  return registry.groups[groupId] ?? null
}

/** One entry by id, or null. Accepts a legacyKey too — resolved at build time. */
export function item (id) {
  return ITEMS.get(id) ?? ITEMS.get(LEGACY.get(id)) ?? null
}

/**
 * A group's entries, in declared part order.
 * Returns [{ part, name, items }]. Parts with no entries are dropped, so a
 * group that has not filled part 4 yet simply does not show one.
 */
export function partsOf (groupId) {
  const g = group(groupId)
  if (!g) return []
  const seen = []
  for (const it of g.items) if (!seen.includes(it.part)) seen.push(it.part)
  return seen
    .sort((a, b) => a - b)
    .map(part => ({
      part,
      name: g.parts?.[part] ?? `parte ${part}`,
      items: g.items.filter(it => it.part === part)
    }))
}

/**
 * Gating — which containers a child may open.
 *
 * `gating.current` names the furthest released container by id. `allowPrior`
 * says whether everything before it stays open. Position comes from the
 * declared `number` on the structure row, never from the id's characters.
 */
export function isUnlocked (groupId) {
  const rows = registry.structure
  const here = rows.find(s => s.id === groupId)
  const current = rows.find(s => s.id === gating.current)
  if (!here || !current) return false
  if (!here.populated) return false
  if (here.number === current.number) return true
  return gating.allowPrior && here.number < current.number
}

export default registry
